# Generated by Django 5.0.6 on 2024-06-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='categoria',
            field=models.CharField(
                choices=[
                    ('FILME', 'Filme'),
                    ('SERIE', 'Série'),
                    ('MUSICA', 'Musica'),
                    ('CURSO', 'Curso'),
                    ('OUTROS', 'Outros'),
                ],
                max_length=15,
            ),
        ),
    ]
